openapi: 3.0.0
info:
  title: RAG Chatbot API for Physical AI & Humanoid Robotics Platform
  description: API for the RAG-based chatbot functionality
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.your-platform.com
    description: Production server

paths:
  /api/chat/query:
    post:
      summary: Process a user query using RAG
      description: Processes user queries with both general knowledge and context-specific responses based on selected text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            properties:
              query:
                type: string
                description: The user's query
                example: "Explain forward kinematics in robotics"
              context:
                type: string
                description: Optional selected text context for specific queries
                example: "Forward kinematics is the use of kinematic equations to determine the position of the end-effector..."
              user_id:
                type: string
                description: Optional user identifier
                example: "user-12345"
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The chatbot's response
                    example: "Forward kinematics is the process of determining the position and orientation of the end-effector..."
                  sources:
                    type: array
                    items:
                      type: string
                    description: List of document sources used in the response
                    example: ["/docs/module3-kinematics", "/docs/module6-motion-planning"]
                  context_type:
                    type: string
                    enum: [general, specific_text]
                    description: Indicates whether response was based on general knowledge or specific context
        '400':
          description: Bad request - missing required parameters
        '500':
          description: Internal server error

  /api/chat/session:
    post:
      summary: Create a new chat session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: Optional user identifier
      responses:
        '201':
          description: Session created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                    example: "session-abc123"
        '500':
          description: Internal server error

  /api/content/ingest:
    post:
      summary: Ingest content for RAG indexing
      description: Add or update content in the vector database for RAG queries
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content_id:
                  type: string
                  description: Unique identifier for the content
                title:
                  type: string
                  description: Title of the content
                content:
                  type: string
                  description: The content to be indexed
                source_path:
                  type: string
                  description: Path to the original content
      responses:
        '200':
          description: Content successfully ingested
        '400':
          description: Bad request - missing required parameters
        '500':
          description: Internal server error